// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeG4D3l7wLMK-C5gf8QEEHjr4SD7HHnz0',
    appId: '1:6435654151:web:01be17be788c336801b8a2',
    messagingSenderId: '6435654151',
    projectId: 'mynotes-44140',
    authDomain: 'mynotes-44140.firebaseapp.com',
    storageBucket: 'mynotes-44140.appspot.com',
    measurementId: 'G-NT9L8M1FTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKhtkok22qdGYIpauiM_q0hFvZBIKBkPQ',
    appId: '1:6435654151:android:0221e3c3965a65d601b8a2',
    messagingSenderId: '6435654151',
    projectId: 'mynotes-44140',
    storageBucket: 'mynotes-44140.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxlwOAubOw1Xd0EEWaulC9Rmo4jkoJQPA',
    appId: '1:6435654151:ios:d6b9d500ae036f3c01b8a2',
    messagingSenderId: '6435654151',
    projectId: 'mynotes-44140',
    storageBucket: 'mynotes-44140.appspot.com',
    iosClientId: '6435654151-24b674k76ut9fhopmd72o2r2i83kevsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxlwOAubOw1Xd0EEWaulC9Rmo4jkoJQPA',
    appId: '1:6435654151:ios:d6b9d500ae036f3c01b8a2',
    messagingSenderId: '6435654151',
    projectId: 'mynotes-44140',
    storageBucket: 'mynotes-44140.appspot.com',
    iosClientId: '6435654151-24b674k76ut9fhopmd72o2r2i83kevsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
